# Generated by Django 4.1.4 on 2022-12-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0004_momentfact_fact_pct_fact_posture_fact_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentfact',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
