# Generated by Django 4.1.4 on 2022-12-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0005_momentfact_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='posture',
        ),
        migrations.AddField(
            model_name='fact',
            name='only_precision',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
