# Generated by Django 4.1.4 on 2022-12-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0006_remove_fact_posture_fact_only_precision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='moment',
        ),
        migrations.AddField(
            model_name='fact',
            name='full_time',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MomentFact',
        ),
    ]
