# Generated by Django 4.1.4 on 2022-12-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0007_remove_fact_moment_fact_full_time_delete_momentfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforematchstat',
            name='goals_conceded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beforematchstat',
            name='goals_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='success',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
