# Generated by Django 4.1.4 on 2022-12-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0008_alter_beforematchstat_goals_conceded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='only_precision',
            new_name='all_matches',
        ),
    ]
