# Generated by Django 4.1.4 on 2023-01-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0010_beforematchstat_avg_cards_against_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforematchstat',
            name='list_confrontations',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='beforematchstat',
            name='list_similaires_betting',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='beforematchstat',
            name='list_similaires_ppg',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='beforematchstat',
            name='list_similaires_ppg2',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
