# Generated by Django 4.1.4 on 2023-01-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0011_beforematchstat_list_confrontations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforematchstat',
            name='list_confrontations',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='beforematchstat',
            name='list_similaires_betting',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='beforematchstat',
            name='list_similaires_ppg',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='beforematchstat',
            name='list_similaires_ppg2',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
