# Generated by Django 4.1.7 on 2023-06-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0013_beforematchstat_list_intercepts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmatch',
            name='away_half_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resultmatch',
            name='home_half_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
