# Generated by Django 4.1.7 on 2023-08-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0016_teamprofilematch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforematchstat',
            name='score_elo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
