# Generated by Django 4.1.7 on 2023-08-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0017_beforematchstat_score_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforematchstat',
            name='ga_expected',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beforematchstat',
            name='gs_expected',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beforematchstat',
            name='probabilite_elo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
