# Generated by Django 4.1.7 on 2023-08-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0018_beforematchstat_ga_expected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beforematchstat',
            name='points',
        ),
        migrations.AlterField(
            model_name='beforematchstat',
            name='ga_expected',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='beforematchstat',
            name='gs_expected',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='beforematchstat',
            name='ppg',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='beforematchstat',
            name='probabilite_elo',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='beforematchstat',
            name='score_elo',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
