# Generated by Django 4.1.7 on 2023-09-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0020_beforematchstat_total_ga_expected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beforematchstat',
            name='total_ga_expected',
        ),
        migrations.RemoveField(
            model_name='beforematchstat',
            name='total_gs_expected',
        ),
        migrations.AddField(
            model_name='beforematchstat',
            name='expected_goals',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
