# Generated by Django 4.1 on 2023-11-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0022_alter_beforematchstat_expected_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamprofilematch',
            old_name='clean',
            new_name='domination',
        ),
        migrations.RenameField(
            model_name='teamprofilematch',
            old_name='pression',
            new_name='ranking',
        ),
        migrations.RemoveField(
            model_name='teamprofilematch',
            name='date',
        ),
    ]
