# Generated by Django 4.1.4 on 2022-12-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editioncompetition',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
