# Generated by Django 4.1.4 on 2022-12-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitionApp', '0002_editioncompetition_is_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='competition',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
