# Generated by Django 4.1.4 on 2022-12-25 09:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competitionApp', '0004_typecompetition_competition_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_rankings', to='competitionApp.editioncompetition')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('mj', models.IntegerField(blank=True, default=0, null=True)),
                ('win', models.IntegerField(blank=True, default=0, null=True)),
                ('draw', models.IntegerField(blank=True, default=0, null=True)),
                ('lose', models.IntegerField(blank=True, default=0, null=True)),
                ('gs', models.IntegerField(blank=True, default=0, null=True)),
                ('ga', models.IntegerField(blank=True, default=0, null=True)),
                ('gd', models.IntegerField(blank=True, default=0, null=True)),
                ('form', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pts', models.IntegerField(blank=True, default=0, null=True)),
                ('cs', models.IntegerField(blank=True, default=0, null=True)),
                ('btts', models.IntegerField(blank=True, default=0, null=True)),
                ('avg_gs', models.FloatField(blank=True, default=0.0, null=True)),
                ('avg_ga', models.FloatField(blank=True, default=0.0, null=True)),
                ('p1_5', models.FloatField(blank=True, default=0.0, null=True)),
                ('p2_5', models.FloatField(blank=True, default=0.0, null=True)),
                ('m3_5', models.FloatField(blank=True, default=0.0, null=True)),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_lignes', to='competitionApp.editioncompetition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lignes_rankings', to='competitionApp.editioncompetition')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
