# Generated by Django 4.1.4 on 2023-01-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamApp', '0002_alter_editionteam_options_alter_team_options_and_more'),
        ('competitionApp', '0006_alter_editioncompetition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneranking',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_lignes', to='competitionApp.ranking'),
        ),
        migrations.AlterField(
            model_name='ligneranking',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lignes_rankings', to='teamApp.editionteam'),
        ),
    ]
