# Generated by Django 4.1.4 on 2023-01-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitionApp', '0008_ligneranking_ppg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ligneranking',
            options={'ordering': ['level']},
        ),
        migrations.AddField(
            model_name='ligneranking',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
