# Generated by Django 4.1.4 on 2023-01-23 16:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fixtureApp', '0005_remove_match_referer_delete_referer'),
        ('competitionApp', '0009_alter_ligneranking_options_ligneranking_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('ppg', models.FloatField(blank=True, null=True)),
                ('avg_goals', models.FloatField(blank=True, null=True)),
                ('avg_fouls', models.FloatField(blank=True, null=True)),
                ('avg_corners', models.FloatField(blank=True, null=True)),
                ('avg_shots', models.FloatField(blank=True, null=True)),
                ('avg_shots_target', models.FloatField(blank=True, null=True)),
                ('avg_offside', models.FloatField(blank=True, null=True)),
                ('avg_cards', models.FloatField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_stats', to='competitionApp.editioncompetition')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_stats', to='fixtureApp.match')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
