# Generated by Django 4.1.4 on 2023-01-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitionApp', '0010_competitionstat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionstat',
            old_name='avg_cards',
            new_name='avg_red_cards',
        ),
        migrations.RenameField(
            model_name='competitionstat',
            old_name='ppg',
            new_name='avg_yellow_cards',
        ),
    ]
