# Generated by Django 4.1.4 on 2023-01-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitionApp', '0011_rename_avg_cards_competitionstat_avg_red_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionstat',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edition_stats', to='competitionApp.editioncompetition'),
        ),
        migrations.AlterField(
            model_name='competitionstat',
            name='ranking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking_stats', to='competitionApp.ranking'),
        ),
    ]
