# Generated by Django 4.1.4 on 2023-02-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitionApp', '0012_alter_competitionstat_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
