# Generated by Django 4.1.4 on 2023-02-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitionApp', '0013_ranking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='identifiant',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pays',
            name='abr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
