# Generated by Django 4.1.7 on 2023-07-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitionApp', '0015_alter_competition_logo_alter_pays_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecompetition',
            name='etiquette',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
