# Generated by Django 4.1.7 on 2023-08-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitionApp', '0016_typecompetition_etiquette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.ImageField(blank=True, default='images/competitions/default.png', max_length=255, null=True, upload_to='images/competitions/'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='flag',
            field=models.ImageField(blank=True, default='images/pays/default.png', max_length=255, null=True, upload_to='images/pays/'),
        ),
    ]
