# Generated by Django 4.1 on 2023-11-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitionApp', '0017_alter_competition_logo_alter_pays_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['type__etiquette', 'pays', 'name']},
        ),
        migrations.AlterModelOptions(
            name='ligneranking',
            options={'ordering': ['-ranking__date', 'level']},
        ),
    ]
