# Generated by Django 4.1.3 on 2022-11-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('etiquette', models.CharField(max_length=255)),
                ('classe', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
