# Generated by Django 4.1.4 on 2022-12-13 21:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='static/images/team/')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays_du_team', to='competitionApp.pays')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditionTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_team', to='competitionApp.editioncompetition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_edition', to='teamApp.team')),
            ],
            options={
                'ordering': ['-edition'],
            },
        ),
    ]
