# Generated by Django 4.1.4 on 2023-02-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamApp', '0002_alter_editionteam_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='color1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='color2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_club',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
