# Generated by Django 4.1.7 on 2023-06-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamApp', '0003_team_abr_team_color1_team_color2_team_is_club_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_club',
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='media/images/teams/default.png', max_length=255, null=True, upload_to='static/images/teams/'),
        ),
    ]
