# Generated by Django 4.1.7 on 2023-08-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamApp', '0004_remove_team_is_club_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='images/teams/default.png', max_length=255, null=True, upload_to='images/teams/'),
        ),
    ]
