# Generated by Django 4.1.4 on 2023-02-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionApp', '0003_predictionscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionscore',
            name='home_score',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='predictionscore',
            name='pct',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
