# Generated by Django 4.1.4 on 2023-02-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionApp', '0004_alter_predictionscore_home_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionscore',
            options={'ordering': ['match', '-pct', 'is_checked']},
        ),
    ]
