# Generated by Django 4.1.3 on 2022-11-26 09:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, default='', null=True)),
                ('finish_date', models.DateField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditionCompetition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_edition', to='features.competition')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_team', to='features.edition')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditionTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_team', to='features.editioncompetition')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays_du_team', to='features.pays')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, default='', null=True)),
                ('home_score', models.IntegerField(blank=True, default=0, null=True)),
                ('away_score', models.IntegerField(blank=True, default=0, null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('home_half_score', models.IntegerField(blank=True, default=0, null=True)),
                ('away_half_score', models.IntegerField(blank=True, default=0, null=True)),
                ('result_half', models.CharField(blank=True, max_length=255, null=True)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='features.editionteam')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_du_match', to='features.editioncompetition')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='features.editionteam')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('minute', models.CharField(blank=True, max_length=255, null=True)),
                ('is_penalty', models.BooleanField(blank=True, max_length=255, null=True)),
                ('home_half_score', models.IntegerField(blank=True, default=0, null=True)),
                ('away_half_score', models.IntegerField(blank=True, default=0, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_du_match', to='features.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_du_goal', to='features.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraInfosMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('home_shots', models.IntegerField(blank=True, default=0, null=True)),
                ('away_shots', models.IntegerField(blank=True, default=0, null=True)),
                ('home_shots_on_target', models.IntegerField(blank=True, default=0, null=True)),
                ('away_shots_on_target', models.IntegerField(blank=True, default=0, null=True)),
                ('home_corners', models.IntegerField(blank=True, default=0, null=True)),
                ('away_corners', models.IntegerField(blank=True, default=0, null=True)),
                ('home_fouls', models.IntegerField(blank=True, default=0, null=True)),
                ('away_fouls', models.IntegerField(blank=True, default=0, null=True)),
                ('home_offsides', models.IntegerField(blank=True, default=0, null=True)),
                ('away_offsides', models.IntegerField(blank=True, default=0, null=True)),
                ('home_yellow_cards', models.IntegerField(blank=True, default=0, null=True)),
                ('away_yellow_cards', models.IntegerField(blank=True, default=0, null=True)),
                ('home_red_cards', models.IntegerField(blank=True, default=0, null=True)),
                ('away_red_cards', models.IntegerField(blank=True, default=0, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_match', to='features.match')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='editionteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_edition', to='features.team'),
        ),
        migrations.AddField(
            model_name='competition',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays_de_competition', to='features.pays'),
        ),
    ]
