# Generated by Django 4.1.3 on 2022-12-01 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_edition_finish_date_alter_edition_start_date_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='BeforeMatchStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('ppg', models.FloatField(blank=True, null=True)),
                ('goals_scored', models.FloatField(blank=True, null=True)),
                ('avg_goals_scored', models.FloatField(blank=True, null=True)),
                ('goals_conceded', models.FloatField(blank=True, null=True)),
                ('avg_goals_conceded', models.FloatField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_stat_match', to='features.match')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_stat_match', to='features.editionteam')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
