# Generated by Django 4.1.3 on 2022-12-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_remove_edition_finish_date_remove_edition_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='start_date',
        ),
        migrations.AddField(
            model_name='editioncompetition',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editioncompetition',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_match', to='features.editionteam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_match', to='features.editionteam'),
        ),
    ]
