# Generated by Django 4.1.3 on 2022-12-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_remove_edition_finish_date_remove_edition_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='flag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='stockage/images/pays/'),
        ),
    ]
