# Generated by Django 4.1.3 on 2022-12-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_pays_flag_alter_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pays',
            name='flag',
        ),
        migrations.AddField(
            model_name='pays',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='stockage/images/pays/'),
        ),
    ]
