# Generated by Django 4.1.3 on 2022-12-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_remove_pays_flag_pays_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pays',
            old_name='logo',
            new_name='flag',
        ),
    ]
