# Generated by Django 4.1.3 on 2022-12-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_rename_logo_pays_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='stockage/images/team/'),
        ),
    ]
