# Generated by Django 4.1.3 on 2022-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='flag',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='images/pays/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='images/team/'),
        ),
    ]
