# Generated by Django 4.1.3 on 2022-12-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_alter_pays_flag_alter_team_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='editioncompetition',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='editionteam',
            options={'ordering': ['-edition']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='pays',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='match',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_penalty',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
