# Generated by Django 4.1.3 on 2022-12-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_alter_edition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
