# Generated by Django 4.1.4 on 2022-12-29 01:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competitionApp', '0005_ranking_ligneranking'),
        ('fixtureApp', '0002_alter_match_options_match_is_first_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays_referer', to='competitionApp.pays')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='match',
            name='referer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer_du_match', to='fixtureApp.referer'),
        ),
    ]
