# Generated by Django 4.1.4 on 2022-12-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtureApp', '0003_referer_match_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
