# Generated by Django 4.1.4 on 2022-12-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtureApp', '0004_alter_referer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='referer',
        ),
        migrations.DeleteModel(
            name='Referer',
        ),
    ]
