# Generated by Django 4.1.4 on 2023-01-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtureApp', '0005_remove_match_referer_delete_referer'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_predict',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
