# Generated by Django 4.1.4 on 2023-02-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtureApp', '0006_match_is_predict'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_facted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
