# Generated by Django 4.1.7 on 2023-06-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtureApp', '0007_match_is_facted'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_compared',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
