# Generated by Django 4.1.7 on 2023-07-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtureApp', '0010_alter_match_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_stated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
