# Generated by Django 4.1.7 on 2023-09-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtureApp', '0011_match_is_stated'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_compared_elo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
