# Generated by Django 4.1 on 2023-11-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtureApp', '0012_match_is_compared_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_profiled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
